name: my_artist_demo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  image_picker: ^1.2.1
  html2md: ^1.3.2
  http: ^1.6.0
  intl: ^0.20.2
  flutter_switch: ^0.3.2
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  flutter_screenutil: ^5.9.3
  hive: ^3.0.0-dev
  hive_flutter: ^2.0.0-dev
  get: ^4.6.5
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  permission_handler: ^12.0.1
  package_info_plus: ^8.0.0
  device_info_plus: ^12.3.0
  dropdown_search: ^6.0.2
  in_app_update: ^4.2.5
  connectivity_plus: ^7.0.0
  photo_manager: ^3.8.3
  camera: ^0.11.3
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  geocoding: ^4.0.0
  google_api_headers: ^4.6.2
  location: ^8.0.1
  json_annotation: ^4.9.0
  popup_menu_plus: ^0.0.6
  photo_view: ^0.15.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  path_provider: ^2.1.5
  share_plus: ^12.0.1
    #  open_filex: ^4.5.0
  flutter_html: ^3.0.0
  video_player: ^2.10.1
  youtube_player_flutter: ^9.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:


  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: PoppinsBold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: PoppinsLight
      fonts:
        - asset: fonts/Poppins-Light.ttf
