name: my_artist_demo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  flutter_screenutil: ^5.9.3
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.2
  hive: ^3.0.0-dev
  hive_flutter: ^2.0.0-dev
  path_provider: ^2.1.5
  get: ^4.6.5
  in_app_update: ^4.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:


  uses-material-design: true

